---
title: "not-used"
author: "YinCY"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# prepare 18 science
```{r}
library(data.table)
library(EnsDb.Mmusculus.v79)
library(scran)
library(scater)
library(magrittr)
library(dplyr)

park_kidney <- fread("../data/kidney/kidney-map/18science/GSE107585_Mouse_kidney_single_cell_datamatrix.txt", 
                    sep = "\t", 
                    header = F) %>% 
    as.data.frame()

park_kidney[1:10, 1:10]
clusters <- park_kidney[1, , drop = T] %>% .[-1] %>% as.integer()
clusters %>% length()
clusters %>% head
colnames(park_kidney) <- c("symbol", paste("cell_", colnames(park_kidney)[-1] %>% sub(pattern = "V", replacement = "", x = .) %>% as.integer() %>% magrittr::add(-1), sep = ""))
park_kidney[1:20, 1:10]

coldata <- data.frame(clusters = clusters)

rowdata <- data.frame(symbol = park_kidney[-1, 1])
EnsDb.Mmusculus.v79 %>% columns()
rowdata$ensembl <- mapIds(EnsDb.Mmusculus.v79, keys = rowdata$symbol, keytype = "SYMBOL", column = "GENEID")
rowdata <- rowdata %>% dplyr::filter(!is.na(rowdata$ensembl))
rownames(rowdata) <- rowdata$ensembl

counts <- park_kidney[-1, ]
counts[1:20, 1:10]
counts <- left_join(rowdata, counts, by = c("symbol" = "symbol"))
counts <- counts %>% dplyr::filter(!is.na(ensembl)) 
rownames(counts) <- counts$ensembl
counts[1:20, 1:10]

park_kidney_sce <- SingleCellExperiment(assays = list(counts = counts[, -c(1, 2)] %>% as.matrix() %>% as(., "CsparseMatrix")), 
                                        rowData = rowdata, 
                                        colData = coldata)
park_kidney_sce <- computeSumFactors(park_kidney_sce, clusters = park_kidney_sce$clusters)
sizeFactors(park_kidney_sce) %>% range
park_kidney_sce <- logNormCounts(x = park_kidney_sce, 
                                 size.factors = sizeFactors(park_kidney_sce), 
                                 transform = "log")
cell_type <- c("1" = "Endo", "2" = "Podo", "3" = "PT", 
               "4" = "LOH", "5" = "DCT", "6" = "CD-PC", 
               "7" = "CD-IC", "8" = "CD-Trans", "9" = "Novel1", 
               "10" = "Fib", "11" = "Macro", "12" = "Neutro", 
               "13" = "B cell", "14" = "T cell", "15" = "NK", 
               "16" = "Novel2")
colData(park_kidney_sce)$cell_type <- cell_type[colData(park_kidney_sce)$clusters]
colData(park_kidney_sce)

saveRDS(park_kidney_sce, "../data/kidney/kidney-map/18science/park_kidney_sce.rds")
park_kidney_sce <- readRDS("../data/kidney/kidney-map/18science/park_kidney_sce.rds")
park_kidney_sce
plotExpression(park_kidney_sce, x = "cell_type", 
               features = idconv("Cd74"))
```

# prepare macrophage reference data
```{r}
library(SingleCellExperiment)
library(readxl)
library(EnsDb.Mmusculus.v79)
library(magrittr)
source("helper-funs.R")

macrophages <- read_xlsx("../data/kidney/kidney-map/macrophage/PRJCA003940.xlsx", 
                         sheet = 1)
macrophages <- macrophages[, 1:7]
macrophages$geneID %>% duplicated() %>% table
macrophages <- aggregate(macrophages[, 2:7], by = list(symbol = macrophages[, 1, drop = T]), FUN = sum)

columns(EnsDb.Mmusculus.v79)
macrophages$ensembl <- mapIds(EnsDb.Mmusculus.v79, 
                             keys = macrophages$symbol, 
                             keytype = "SYMBOL", 
                             column = "GENEID")
macrophages <- macrophages %>% dplyr::relocate(ensembl)
macrophages <- macrophages %>% dplyr::filter(!is.na(ensembl))
macrophages$ensembl %>% duplicated() %>% table
rownames(macrophages) <- macrophages$ensembl

lib_size <- colSums(macrophages[, 3:8])
macrophage_cpm <- apply(macrophages[, 3:8], 1, function(x){round((x / lib_size)*1e6, 2)}) %>% t() %>% as.data.frame()
macrophage_cpm$ensembl <- rownames(macrophage_cpm)
macrophage_cpm <- macrophage_cpm %>% dplyr::relocate(ensembl)

filter_index <- (rowSums(macrophage_cpm[, 2:4] > 1) >= 2) | (rowSums(macrophage_cpm[, 5:7] > 1) >= 2)
filter_index %>% table


ref_macrophage_sce <- SingleCellExperiment(
    assays = list(count = macrophages[filter_index, 3:8], 
                  cpm = macrophage_cpm[filter_index, 2:7]), 
    rowData = data.frame(ensembl = macrophages[filter_index, 1, drop = T], 
                         symbol = macrophages[filter_index, 2, drop = T],
                         row.names = macrophages[filter_index, 1, drop = T]), 
    colData = data.frame(group = rep(c("monocyte derived", "embryonic derived"), each = 3), 
                         cell_type = rep(c("monocytes macrophage", "embryonic macrophage"), each  =3),
                         row.names = colnames(macrophage_cpm)[2:7])
)
ref_macrophage_sce
rowData(ref_macrophage_sce)
colData(ref_macrophage_sce)

saveRDS(ref_macrophage_sce, "../data/kidney/kidney-map/macrophage/ref_macrophage_sce.rds")
```


