---
title: "Untitled"
author: "yincy"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# SRP135960
```{r}
library(magrittr)
library(loomR)
source("R/loom2SCE.R")


all_loom <- connect("../data/kidney/kidney-map/SRP135960/l5_all.loom", mode = "r+")
all_loom[["col_attrs"]] %>% as.list() %>% .[["names"]]
all_loom[["col_attrs/Tissue"]][] %>% table
tissues <- c("Sympath", "DRG")
col_ids <- which(all_loom[["col_attrs/Tissue"]][] %in% tissues)
col_ids %>% str

DRG_Sym_loom <- subset.loom(x = all_loom, 
                            m = col_ids, 
                            filename = "../data/kidney/kidney-map/SRP135960/l5_DRG_Sym.loom")
all_loom$close_all()
DRG_Sym_loom <- connect("../data/kidney/kidney-map/SRP135960/l5_DRG_Sym.loom")
drg_sym_sce <- loom2SCE(DRG_Sym_loom)
drg_sym_sce %>% colData
colData(drg_sym_sce)$TaxonomyRank4 %>% table

saveRDS(drg_sym_sce, "../data/kidney/kidney-map/SRP135960/drg_sym_sce.rds")
```


```{r}
drg_sym_sce <- readRDS("../data/kidney/kidney-map/SRP135960/drg_sym_sce.rds")
# quality control
# only retain sensory, sympathetic neurons and Schwann cells and sympathe
cells_to_remove <- c("Satellite glia", "Vascular endothelial cells", "Vascular smooth muscle cells")
colData(drg_sym_sce)[, c("TaxonomyRank4", "Tissue")] %>% table
drg_sym_sce <- drg_sym_sce[, !(drg_sym_sce$TaxonomyRank4 %in% cells_to_remove)]

# normalization
library(scran)

drg_sym_sce <- computePooledFactors(drg_sym_sce, clusters = colData(drg_sym_sce)$TaxonomyRank4)
drg_sym_sce <- logNormCounts(drg_sym_sce)

# model gene variance
variance <- modelGeneVar(drg_sym_sce, block = colData(drg_sym_sce)$batch)
hvgs <- getTopHVGs(variance, 
                   fdr.threshold = 0.001)
hvgs %>% str

# dimensional reduction
library(scater)
npcs <- calculatePCA(logcounts(drg_sym_sce), subset_row = hvgs)

library(PCAtools)
elbow <- findElbowPoint(attr(npcs, "percentVar"))
reducedDim(drg_sym_sce, "PCA") <- npcs[, 1:elbow]
drg_sym_sce <- runTSNE(drg_sym_sce, dimred = "PCA")

source("R/idconv.R")
plotTSNE(drg_sym_sce, 
         # colour_by = "TaxonomyRank4", 
         colour_by = idconv("Snap25"))

# clustering
library(bluster)
clusters <- clusterRows(reducedDim(drg_sym_sce, "PCA"), 
                        BLUSPARAM = NNGraphParam(cluster.fun = "louvain", k = 40))
clusters %>% table
colLabels(drg_sym_sce) <- clusters
plotTSNE(drg_sym_sce, colour_by = "label", text_by = "label")
saveRDS(drg_sym_sce, "../data/kidney/kidney-map/SRP135960/drg_sym_sce.rds")
```
